# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-16 06:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sl_sm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bankdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField()),
                ('bank_name', models.CharField(max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sl_sm.userreg')),
            ],
        ),
    ]
