# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-16 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sl_sm', '0002_bankdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='account_number',
            field=models.CharField(max_length=50),
        ),
    ]
