# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-16 06:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sl_sm', '0004_auto_20181216_0629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discounts',
            old_name='p_id',
            new_name='pname',
        ),
    ]
